### ISSUE TITLE
Looking for coding standards

### ISSUE THREAD

**Issue by mschuetterle** [slimbootloader/documentation#38]
I was not able to find a document in regards to coding standards for the SBL. Both, not in source and also not in the documentation.
Maybe I have missed something or there could be a description been added.
Also, a chapter could helpful of what needs to be done if a developer wants to upstream patches.

**Comment by rprangar** [comment]
Hello Markus

A contributions page has been setup https://slimbootloader.github.io/developer-guides/contributions.html with [commit](https://github.com/slimbootloader/documentation/commit/3910b8509db4d2163034440cd5d94c72cdc1ed57)

Thanks
Ravi
